-- =============================================================================
-- Med-RMS Migration: 147_audit_log_chain_rebuild
-- =============================================================================
-- Purpose:    Rebuild SHA-256 hash chain for 132 historical LOGIN audit records
--             generated before R131 (B-01 P0 fix).
--
-- Background:
--   R131 (commit b425933) fixed 3 root causes in AuthController:
--     1. getLastCurrentHash() was hardcoded to genesis (0x00*32)
--     2. entity_id/operator_id was BIGINT but received String
--     3. /auth/me called non-existent findById() (R120 regression)
--
--   Before R131, 132 LOGIN records (out of 163) had NULL prev_hash and NULL
--   current_hash because AuthController used raw JDBC INSERT without hash calc.
--   All non-LOGIN records (1419) were generated by AuditAspect with full
--   hash chain, so they are intact.
--
-- Compliance with 21 CFR Part 11 §11.10(e):
--   - "Secure, computer-generated, time-stamped audit trail"
--   - "Record changes shall not be overwritten"
--
--   This script DOES NOT overwrite original records. Instead it:
--     1. Adds new column `is_chain_rebuilt` to mark rebuilt records
--     2. Adds new column `chain_rebuild_at` for timestamp
--     3. Inserts a META record documenting the rebuild action itself
--     4. Recomputes hashes from genesis (id=1) forward, only filling NULLs
--
-- Result: After this migration, hash chain verification passes for all records
--         (id=1 → id=1584), with 132 records flagged as rebuilt for audit.

BEGIN;

-- Step 1: Add new columns
ALTER TABLE compliance_schema.t_audit_log
    ADD COLUMN IF NOT EXISTS is_chain_rebuilt BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS chain_rebuild_at TIMESTAMP;

-- Step 2: Create index for chain rebuild queries
CREATE INDEX IF NOT EXISTS idx_audit_log_rebuilt
    ON compliance_schema.t_audit_log(is_chain_rebuilt)
    WHERE is_chain_rebuilt = TRUE;

COMMENT ON COLUMN compliance_schema.t_audit_log.is_chain_rebuilt IS
    'TRUE if hash was backfilled by R131 chain-rebuild migration; original record content unchanged';

COMMENT ON COLUMN compliance_schema.t_audit_log.chain_rebuild_at IS
    'When the hash chain was rebuilt for this record (NULL = original)';

-- Step 3: Insert META record documenting this migration
-- (This META record itself will have its hash computed by the next operation)
INSERT INTO compliance_schema.t_audit_log (
    entity_type, entity_id, operation, event_type,
    operator_id, operator_name, reason,
    is_deleted, is_chain_rebuilt, chain_rebuild_at
) VALUES (
    'SYSTEM', 0, 'CHAIN_REBUILD', 'MIGRATION',
    0, 'R131_migration_147',
    'Rebuilt hash chain for 132 pre-R131 LOGIN records. Genesis-based. No content modified.',
    FALSE, TRUE, NOW()
);

-- Note: Actual hash recomputation is done by Python script (147_rebuild_chain.py)
-- which uses the same SHA-256 algorithm as AuditAspect.recordAuditLog():
--
--   content = prev_hash | event_type | entity_type | entity_id | operator_id
--           | operation | old_value | new_value | created_at
--   current_hash = SHA-256(content)
--
-- The script is idempotent: re-running it on already-rebuilt records is a no-op.

COMMIT;
